kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-manager
  namespace: parrallel-coin-flipper
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-reader-manager
  namespace: parrallel-coin-flipper
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-manager-binding
  namespace: parrallel-coin-flipper
subjects:
- kind: ServiceAccount
  name: default
  namespace: parrallel-coin-flipper
roleRef:
  kind: ClusterRole
  name: namespace-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-reader-manager-binding
  namespace: parrallel-coin-flipper
subjects:
- kind: ServiceAccount
  name: default
  namespace: parrallel-coin-flipper
roleRef:
  kind: ClusterRole
  name: secret-reader-manager
  apiGroup: rbac.authorization.k8s.io